# Generated by Django 4.0.2 on 2022-03-07 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tags_alter_room_code_alter_room_id'),
        ('api', '0003_room_current_song'),
    ]

    operations = [
    ]
